In [1]:
from model.test import train
from dataset import *
from tools import evaluate

from sklearn import metrics
from sklearn.preprocessing import LabelEncoder 
from sklearn.cluster import KMeans, BisectingKMeans, Birch, SpectralClustering, AgglomerativeClustering, FeatureAgglomeration

result = [[[], [], []], [[], [], []], [[], [], []]]

In [2]:
adata, n_cluster = get_visium_fluo_data()
train(adata, lr=1e-3, radius=300, node2vec_p=4, node2vec_q=.25, louvain_resolution=.4, components_features=30, walk_length=25)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[0][0].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py:62: UserWarning: `flavor='seurat_v3'` expects raw count data, but non-integers were found.
  warnings.warn(


>>> dataset name: visium_fluo, size: (2800, 16562), cluster: 15.
>>> The graph contains 19128 edges, average 6.831428571428572 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
>>> finish louvain, begin to prune graph
>>> pruned graph contains 16296 edges, average 5.82 edges per node.


>>> node2vec: 100%|██████████| 200/200 [05:29<00:00,  1.65s/it]


>>> spatial model data(features) size: (2800, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:07<00:00, 65.69it/s] 


>>> Birch: 53.7413


In [3]:
adata, n_cluster = get_visium_fluo_data()
train(adata, lr=1e-3, radius=300, node2vec_p=4, node2vec_q=.25, louvain_resolution=.6, components_features=30, walk_length=25)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[1][0].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py:62: UserWarning: `flavor='seurat_v3'` expects raw count data, but non-integers were found.
  warnings.warn(


>>> dataset name: visium_fluo, size: (2800, 16562), cluster: 15.
>>> The graph contains 19128 edges, average 6.831428571428572 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
>>> finish louvain, begin to prune graph
>>> pruned graph contains 16084 edges, average 5.744285714285715 edges per node.


>>> node2vec: 100%|██████████| 200/200 [01:20<00:00,  2.47it/s]


>>> spatial model data(features) size: (2800, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:04<00:00, 117.43it/s]


>>> Birch: 55.7492


In [4]:
adata, n_cluster = get_visium_fluo_data()
train(adata, lr=1e-3, radius=300, node2vec_p=4, node2vec_q=.25, louvain_resolution=.8, components_features=30, walk_length=25)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[2][0].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py:62: UserWarning: `flavor='seurat_v3'` expects raw count data, but non-integers were found.
  warnings.warn(


>>> dataset name: visium_fluo, size: (2800, 16562), cluster: 15.
>>> The graph contains 19128 edges, average 6.831428571428572 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
>>> finish louvain, begin to prune graph
>>> pruned graph contains 15734 edges, average 5.619285714285715 edges per node.


>>> node2vec: 100%|██████████| 200/200 [03:42<00:00,  1.11s/it]


>>> spatial model data(features) size: (2800, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:04<00:00, 115.44it/s]


>>> Birch: 53.8881


In [5]:
adata, n_cluster = get_visium_fluo_data()
train(adata, lr=1e-3, radius=300, node2vec_p=1, node2vec_q=1, louvain_resolution=.4, components_features=30, walk_length=25)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[0][0].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py:62: UserWarning: `flavor='seurat_v3'` expects raw count data, but non-integers were found.
  warnings.warn(


>>> dataset name: visium_fluo, size: (2800, 16562), cluster: 15.
>>> The graph contains 19128 edges, average 6.831428571428572 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
>>> finish louvain, begin to prune graph
>>> pruned graph contains 16296 edges, average 5.82 edges per node.


>>> node2vec: 100%|██████████| 200/200 [01:18<00:00,  2.53it/s]


>>> spatial model data(features) size: (2800, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:04<00:00, 118.16it/s]


>>> Birch: 65.8037


In [6]:
adata, n_cluster = get_visium_fluo_data()
train(adata, lr=1e-3, radius=300, node2vec_p=1, node2vec_q=1, louvain_resolution=.6, components_features=30, walk_length=25)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[1][0].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py:62: UserWarning: `flavor='seurat_v3'` expects raw count data, but non-integers were found.
  warnings.warn(


>>> dataset name: visium_fluo, size: (2800, 16562), cluster: 15.
>>> The graph contains 19128 edges, average 6.831428571428572 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
>>> finish louvain, begin to prune graph
>>> pruned graph contains 16084 edges, average 5.744285714285715 edges per node.


>>> node2vec: 100%|██████████| 200/200 [03:19<00:00,  1.00it/s]


>>> spatial model data(features) size: (2800, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:04<00:00, 120.24it/s]


>>> Birch: 58.3533


In [7]:
adata, n_cluster = get_visium_fluo_data()
train(adata, lr=1e-3, radius=300, node2vec_p=1, node2vec_q=1, louvain_resolution=.8, components_features=30, walk_length=25)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[2][0].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py:62: UserWarning: `flavor='seurat_v3'` expects raw count data, but non-integers were found.
  warnings.warn(


>>> dataset name: visium_fluo, size: (2800, 16562), cluster: 15.
>>> The graph contains 19128 edges, average 6.831428571428572 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
>>> finish louvain, begin to prune graph
>>> pruned graph contains 15734 edges, average 5.619285714285715 edges per node.


>>> node2vec: 100%|██████████| 200/200 [02:10<00:00,  1.53it/s]


>>> spatial model data(features) size: (2800, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:04<00:00, 117.09it/s]


>>> Birch: 59.5541


In [8]:
adata, n_cluster = get_visium_fluo_data()
train(adata, lr=1e-3, radius=300, node2vec_p=.25, node2vec_q=4, louvain_resolution=.4, components_features=30, walk_length=25)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[0][0].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py:62: UserWarning: `flavor='seurat_v3'` expects raw count data, but non-integers were found.
  warnings.warn(


>>> dataset name: visium_fluo, size: (2800, 16562), cluster: 15.
>>> The graph contains 19128 edges, average 6.831428571428572 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
>>> finish louvain, begin to prune graph
>>> pruned graph contains 16296 edges, average 5.82 edges per node.


>>> node2vec: 100%|██████████| 200/200 [02:25<00:00,  1.38it/s]


>>> spatial model data(features) size: (2800, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:04<00:00, 107.08it/s]


>>> Birch: 53.7571


In [9]:
adata, n_cluster = get_visium_fluo_data()
train(adata, lr=1e-3, radius=300, node2vec_p=.25, node2vec_q=4, louvain_resolution=.6, components_features=30, walk_length=25)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[1][0].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py:62: UserWarning: `flavor='seurat_v3'` expects raw count data, but non-integers were found.
  warnings.warn(


>>> dataset name: visium_fluo, size: (2800, 16562), cluster: 15.
>>> The graph contains 19128 edges, average 6.831428571428572 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
>>> finish louvain, begin to prune graph
>>> pruned graph contains 16084 edges, average 5.744285714285715 edges per node.


>>> node2vec: 100%|██████████| 200/200 [03:35<00:00,  1.08s/it]


>>> spatial model data(features) size: (2800, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:03<00:00, 129.27it/s]


>>> Birch: 47.3291


In [10]:
adata, n_cluster = get_visium_fluo_data()
train(adata, lr=1e-3, radius=300, node2vec_p=.25, node2vec_q=4, louvain_resolution=.8, components_features=30, walk_length=25)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[2][0].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py:62: UserWarning: `flavor='seurat_v3'` expects raw count data, but non-integers were found.
  warnings.warn(


>>> dataset name: visium_fluo, size: (2800, 16562), cluster: 15.
>>> The graph contains 19128 edges, average 6.831428571428572 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
>>> finish louvain, begin to prune graph
>>> pruned graph contains 15734 edges, average 5.619285714285715 edges per node.


>>> node2vec: 100%|██████████| 200/200 [01:32<00:00,  2.17it/s]


>>> spatial model data(features) size: (2800, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:04<00:00, 116.32it/s]


>>> Birch: 61.3118


In [11]:
adata, n_cluster = get_visium_fluo_data()
train(adata, lr=1e-3, radius=300, node2vec_p=4, node2vec_q=.25, louvain_resolution=.4, components_features=30, walk_length=35)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[0][1].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py:62: UserWarning: `flavor='seurat_v3'` expects raw count data, but non-integers were found.
  warnings.warn(


>>> dataset name: visium_fluo, size: (2800, 16562), cluster: 15.
>>> The graph contains 19128 edges, average 6.831428571428572 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
>>> finish louvain, begin to prune graph
>>> pruned graph contains 16296 edges, average 5.82 edges per node.


>>> node2vec: 100%|██████████| 200/200 [05:48<00:00,  1.74s/it]


>>> spatial model data(features) size: (2800, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:04<00:00, 119.86it/s]


>>> Birch: 63.6580


In [12]:
adata, n_cluster = get_visium_fluo_data()
train(adata, lr=1e-3, radius=300, node2vec_p=4, node2vec_q=.25, louvain_resolution=.6, components_features=30, walk_length=35)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[1][1].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py:62: UserWarning: `flavor='seurat_v3'` expects raw count data, but non-integers were found.
  warnings.warn(


>>> dataset name: visium_fluo, size: (2800, 16562), cluster: 15.
>>> The graph contains 19128 edges, average 6.831428571428572 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
>>> finish louvain, begin to prune graph
>>> pruned graph contains 16084 edges, average 5.744285714285715 edges per node.


>>> node2vec: 100%|██████████| 200/200 [05:03<00:00,  1.52s/it]


>>> spatial model data(features) size: (2800, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:04<00:00, 122.28it/s]


>>> Birch: 62.8888


In [13]:
adata, n_cluster = get_visium_fluo_data()
train(adata, lr=1e-3, radius=300, node2vec_p=4, node2vec_q=.25, louvain_resolution=.8, components_features=30, walk_length=35)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[2][1].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py:62: UserWarning: `flavor='seurat_v3'` expects raw count data, but non-integers were found.
  warnings.warn(


>>> dataset name: visium_fluo, size: (2800, 16562), cluster: 15.
>>> The graph contains 19128 edges, average 6.831428571428572 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
>>> finish louvain, begin to prune graph
>>> pruned graph contains 15734 edges, average 5.619285714285715 edges per node.


>>> node2vec: 100%|██████████| 200/200 [04:21<00:00,  1.31s/it]


>>> spatial model data(features) size: (2800, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:04<00:00, 106.95it/s]


>>> Birch: 59.2783


In [14]:
adata, n_cluster = get_visium_fluo_data()
train(adata, lr=1e-3, radius=300, node2vec_p=1, node2vec_q=1, louvain_resolution=.4, components_features=30, walk_length=35)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[0][1].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py:62: UserWarning: `flavor='seurat_v3'` expects raw count data, but non-integers were found.
  warnings.warn(


>>> dataset name: visium_fluo, size: (2800, 16562), cluster: 15.
>>> The graph contains 19128 edges, average 6.831428571428572 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
>>> finish louvain, begin to prune graph
>>> pruned graph contains 16296 edges, average 5.82 edges per node.


>>> node2vec: 100%|██████████| 200/200 [04:53<00:00,  1.47s/it]


>>> spatial model data(features) size: (2800, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:04<00:00, 100.14it/s]


>>> Birch: 59.1954


In [15]:
adata, n_cluster = get_visium_fluo_data()
train(adata, lr=1e-3, radius=300, node2vec_p=1, node2vec_q=1, louvain_resolution=.6, components_features=30, walk_length=35)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[1][1].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py:62: UserWarning: `flavor='seurat_v3'` expects raw count data, but non-integers were found.
  warnings.warn(


>>> dataset name: visium_fluo, size: (2800, 16562), cluster: 15.
>>> The graph contains 19128 edges, average 6.831428571428572 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
>>> finish louvain, begin to prune graph
>>> pruned graph contains 16084 edges, average 5.744285714285715 edges per node.


>>> node2vec: 100%|██████████| 200/200 [04:47<00:00,  1.44s/it]


>>> spatial model data(features) size: (2800, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:04<00:00, 110.28it/s]


>>> Birch: 65.7316


In [16]:
adata, n_cluster = get_visium_fluo_data()
train(adata, lr=1e-3, radius=300, node2vec_p=1, node2vec_q=1, louvain_resolution=.8, components_features=30, walk_length=35)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[2][1].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py:62: UserWarning: `flavor='seurat_v3'` expects raw count data, but non-integers were found.
  warnings.warn(


>>> dataset name: visium_fluo, size: (2800, 16562), cluster: 15.
>>> The graph contains 19128 edges, average 6.831428571428572 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
>>> finish louvain, begin to prune graph
>>> pruned graph contains 15734 edges, average 5.619285714285715 edges per node.


>>> node2vec: 100%|██████████| 200/200 [06:06<00:00,  1.83s/it]


>>> spatial model data(features) size: (2800, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:04<00:00, 109.75it/s]


>>> Birch: 64.4209


In [17]:
adata, n_cluster = get_visium_fluo_data()
train(adata, lr=1e-3, radius=300, node2vec_p=.25, node2vec_q=4, louvain_resolution=.4, components_features=30, walk_length=35)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[0][1].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py:62: UserWarning: `flavor='seurat_v3'` expects raw count data, but non-integers were found.
  warnings.warn(


>>> dataset name: visium_fluo, size: (2800, 16562), cluster: 15.
>>> The graph contains 19128 edges, average 6.831428571428572 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
>>> finish louvain, begin to prune graph
>>> pruned graph contains 16296 edges, average 5.82 edges per node.


>>> node2vec: 100%|██████████| 200/200 [06:09<00:00,  1.85s/it]


>>> spatial model data(features) size: (2800, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:04<00:00, 118.87it/s]


>>> Birch: 60.9130


In [18]:
adata, n_cluster = get_visium_fluo_data()
train(adata, lr=1e-3, radius=300, node2vec_p=.25, node2vec_q=4, louvain_resolution=.6, components_features=30, walk_length=35)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[1][1].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py:62: UserWarning: `flavor='seurat_v3'` expects raw count data, but non-integers were found.
  warnings.warn(


>>> dataset name: visium_fluo, size: (2800, 16562), cluster: 15.
>>> The graph contains 19128 edges, average 6.831428571428572 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
>>> finish louvain, begin to prune graph
>>> pruned graph contains 16084 edges, average 5.744285714285715 edges per node.


>>> node2vec: 100%|██████████| 200/200 [05:02<00:00,  1.51s/it]


>>> spatial model data(features) size: (2800, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:04<00:00, 117.56it/s]


>>> Birch: 56.1931


In [19]:
adata, n_cluster = get_visium_fluo_data()
train(adata, lr=1e-3, radius=300, node2vec_p=.25, node2vec_q=4, louvain_resolution=.8, components_features=30, walk_length=35)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[2][1].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py:62: UserWarning: `flavor='seurat_v3'` expects raw count data, but non-integers were found.
  warnings.warn(


>>> dataset name: visium_fluo, size: (2800, 16562), cluster: 15.
>>> The graph contains 19128 edges, average 6.831428571428572 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
>>> finish louvain, begin to prune graph
>>> pruned graph contains 15734 edges, average 5.619285714285715 edges per node.


>>> node2vec: 100%|██████████| 200/200 [05:23<00:00,  1.62s/it]


>>> spatial model data(features) size: (2800, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:03<00:00, 133.60it/s]


>>> Birch: 59.8636


In [20]:
adata, n_cluster = get_visium_fluo_data()
train(adata, lr=1e-3, radius=300, node2vec_p=4, node2vec_q=.25, louvain_resolution=.4, components_features=30, walk_length=45)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[0][2].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py:62: UserWarning: `flavor='seurat_v3'` expects raw count data, but non-integers were found.
  warnings.warn(


>>> dataset name: visium_fluo, size: (2800, 16562), cluster: 15.
>>> The graph contains 19128 edges, average 6.831428571428572 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
>>> finish louvain, begin to prune graph
>>> pruned graph contains 16296 edges, average 5.82 edges per node.


>>> node2vec: 100%|██████████| 200/200 [09:42<00:00,  2.91s/it]


>>> spatial model data(features) size: (2800, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:04<00:00, 110.32it/s]


>>> Birch: 54.7922


In [21]:
adata, n_cluster = get_visium_fluo_data()
train(adata, lr=1e-3, radius=300, node2vec_p=4, node2vec_q=.25, louvain_resolution=.6, components_features=30, walk_length=45)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[1][2].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py:62: UserWarning: `flavor='seurat_v3'` expects raw count data, but non-integers were found.
  warnings.warn(


>>> dataset name: visium_fluo, size: (2800, 16562), cluster: 15.
>>> The graph contains 19128 edges, average 6.831428571428572 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
>>> finish louvain, begin to prune graph
>>> pruned graph contains 16084 edges, average 5.744285714285715 edges per node.


>>> node2vec: 100%|██████████| 200/200 [12:05<00:00,  3.63s/it]


>>> spatial model data(features) size: (2800, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:05<00:00, 88.37it/s] 


>>> Birch: 62.1269


In [22]:
adata, n_cluster = get_visium_fluo_data()
train(adata, lr=1e-3, radius=300, node2vec_p=4, node2vec_q=.25, louvain_resolution=.8, components_features=30, walk_length=45)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[2][2].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py:62: UserWarning: `flavor='seurat_v3'` expects raw count data, but non-integers were found.
  warnings.warn(


>>> dataset name: visium_fluo, size: (2800, 16562), cluster: 15.
>>> The graph contains 19128 edges, average 6.831428571428572 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
>>> finish louvain, begin to prune graph
>>> pruned graph contains 15734 edges, average 5.619285714285715 edges per node.


>>> node2vec: 100%|██████████| 200/200 [05:56<00:00,  1.78s/it]


>>> spatial model data(features) size: (2800, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:06<00:00, 74.88it/s]


>>> Birch: 62.9441


In [23]:
adata, n_cluster = get_visium_fluo_data()
train(adata, lr=1e-3, radius=300, node2vec_p=1, node2vec_q=1, louvain_resolution=.4, components_features=30, walk_length=45)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[0][2].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py:62: UserWarning: `flavor='seurat_v3'` expects raw count data, but non-integers were found.
  warnings.warn(


>>> dataset name: visium_fluo, size: (2800, 16562), cluster: 15.
>>> The graph contains 19128 edges, average 6.831428571428572 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
>>> finish louvain, begin to prune graph
>>> pruned graph contains 16296 edges, average 5.82 edges per node.


>>> node2vec: 100%|██████████| 200/200 [05:19<00:00,  1.60s/it]


>>> spatial model data(features) size: (2800, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:05<00:00, 95.71it/s] 


>>> Birch: 63.9198


In [24]:
adata, n_cluster = get_visium_fluo_data()
train(adata, lr=1e-3, radius=300, node2vec_p=1, node2vec_q=1, louvain_resolution=.6, components_features=30, walk_length=45)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[1][2].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py:62: UserWarning: `flavor='seurat_v3'` expects raw count data, but non-integers were found.
  warnings.warn(


>>> dataset name: visium_fluo, size: (2800, 16562), cluster: 15.
>>> The graph contains 19128 edges, average 6.831428571428572 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
>>> finish louvain, begin to prune graph
>>> pruned graph contains 16084 edges, average 5.744285714285715 edges per node.


>>> node2vec: 100%|██████████| 200/200 [06:23<00:00,  1.92s/it]


>>> spatial model data(features) size: (2800, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:05<00:00, 90.72it/s] 


>>> Birch: 51.6043


In [25]:
adata, n_cluster = get_visium_fluo_data()
train(adata, lr=1e-3, radius=300, node2vec_p=1, node2vec_q=1, louvain_resolution=.8, components_features=30, walk_length=45)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[2][2].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py:62: UserWarning: `flavor='seurat_v3'` expects raw count data, but non-integers were found.
  warnings.warn(


>>> dataset name: visium_fluo, size: (2800, 16562), cluster: 15.
>>> The graph contains 19128 edges, average 6.831428571428572 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
>>> finish louvain, begin to prune graph
>>> pruned graph contains 15734 edges, average 5.619285714285715 edges per node.


>>> node2vec: 100%|██████████| 200/200 [06:35<00:00,  1.98s/it]


>>> spatial model data(features) size: (2800, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:05<00:00, 90.37it/s] 


>>> Birch: 62.4323


In [26]:
adata, n_cluster = get_visium_fluo_data()
train(adata, lr=1e-3, radius=300, node2vec_p=.25, node2vec_q=4, louvain_resolution=.4, components_features=30, walk_length=45)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[0][2].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py:62: UserWarning: `flavor='seurat_v3'` expects raw count data, but non-integers were found.
  warnings.warn(


>>> dataset name: visium_fluo, size: (2800, 16562), cluster: 15.
>>> The graph contains 19128 edges, average 6.831428571428572 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
>>> finish louvain, begin to prune graph
>>> pruned graph contains 16296 edges, average 5.82 edges per node.


>>> node2vec: 100%|██████████| 200/200 [05:52<00:00,  1.76s/it]


>>> spatial model data(features) size: (2800, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:07<00:00, 69.30it/s] 


>>> Birch: 64.5632


In [27]:
adata, n_cluster = get_visium_fluo_data()
train(adata, lr=1e-3, radius=300, node2vec_p=.25, node2vec_q=4, louvain_resolution=.6, components_features=30, walk_length=45)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[1][2].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py:62: UserWarning: `flavor='seurat_v3'` expects raw count data, but non-integers were found.
  warnings.warn(


>>> dataset name: visium_fluo, size: (2800, 16562), cluster: 15.
>>> The graph contains 19128 edges, average 6.831428571428572 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
>>> finish louvain, begin to prune graph
>>> pruned graph contains 16084 edges, average 5.744285714285715 edges per node.


>>> node2vec: 100%|██████████| 200/200 [05:33<00:00,  1.67s/it]


>>> spatial model data(features) size: (2800, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:05<00:00, 89.55it/s]


>>> Birch: 65.6154


In [28]:
adata, n_cluster = get_visium_fluo_data()
train(adata, lr=1e-3, radius=300, node2vec_p=.25, node2vec_q=4, louvain_resolution=.8, components_features=30, walk_length=45)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[2][2].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/scanpy/preprocessing/_highly_variable_genes.py:62: UserWarning: `flavor='seurat_v3'` expects raw count data, but non-integers were found.
  warnings.warn(


>>> dataset name: visium_fluo, size: (2800, 16562), cluster: 15.
>>> The graph contains 19128 edges, average 6.831428571428572 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
>>> finish louvain, begin to prune graph
>>> pruned graph contains 15734 edges, average 5.619285714285715 edges per node.


>>> node2vec: 100%|██████████| 200/200 [05:20<00:00,  1.60s/it]


>>> spatial model data(features) size: (2800, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:05<00:00, 98.64it/s] 


>>> Birch: 63.6637


In [29]:
import numpy as np

print(np.array(result))

[[[53.74126746 65.80370246 53.75711079]
  [63.65803547 59.19536427 60.91304651]
  [54.79221776 63.91976156 64.56318496]]

 [[55.74921032 58.35331504 47.32914165]
  [62.88878271 65.73163461 56.19314366]
  [62.12688978 51.60430396 65.61536717]]

 [[53.88807692 59.55405323 61.31184849]
  [59.2782995  64.42087031 59.86358364]
  [62.94410786 62.4323372  63.66373052]]]
