In [1]:
from model.test import train
from dataset import *
from tools import evaluate

from sklearn import metrics
from sklearn.preprocessing import LabelEncoder 
from sklearn.cluster import KMeans, BisectingKMeans, Birch, SpectralClustering, AgglomerativeClustering, FeatureAgglomeration

result = [[[], [], []], [[], [], []], [[], [], []]]
sectionid = '151508'

In [2]:
adata, n_cluster = get_dlpfc_data(sectionid)
train(adata, lr=1e-3, radius=150, node2vec_p=4, node2vec_q=.25, louvain_resolution=.4, components_features=30, walk_length=25)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[0][0].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: dlpfc, slice id: 151508, size: (4384, 33538), cluster: 7.
>>> The graph contains 30082 edges, average 6.861770072992701 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.


2022-10-19 22:33:24.552753: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-19 22:33:24.708762: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.


>>> finish louvain, begin to prune graph
>>> pruned graph contains 28426 edges, average 6.484032846715328 edges per node.


>>> node2vec: 100%|██████████| 200/200 [04:06<00:00,  1.23s/it]


>>> spatial model data(features) size: (4384, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:07<00:00, 63.24it/s]


>>> Birch: 35.5320


In [3]:
adata, n_cluster = get_dlpfc_data(sectionid)
train(adata, lr=1e-3, radius=150, node2vec_p=4, node2vec_q=.25, louvain_resolution=.6, components_features=30, walk_length=25)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[1][0].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: dlpfc, slice id: 151508, size: (4384, 33538), cluster: 7.
>>> The graph contains 30082 edges, average 6.861770072992701 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 21140 edges, average 4.822080291970803 edges per node.


>>> node2vec: 100%|██████████| 200/200 [03:59<00:00,  1.20s/it]


>>> spatial model data(features) size: (4384, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:06<00:00, 73.00it/s]


>>> Birch: 34.5577


In [4]:
adata, n_cluster = get_dlpfc_data(sectionid)
train(adata, lr=1e-3, radius=150, node2vec_p=4, node2vec_q=.25, louvain_resolution=.8, components_features=30, walk_length=25)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[2][0].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: dlpfc, slice id: 151508, size: (4384, 33538), cluster: 7.
>>> The graph contains 30082 edges, average 6.861770072992701 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 20530 edges, average 4.68293795620438 edges per node.


>>> node2vec: 100%|██████████| 200/200 [04:04<00:00,  1.22s/it]


>>> spatial model data(features) size: (4384, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:07<00:00, 69.05it/s]


>>> Birch: 43.6144


In [5]:
adata, n_cluster = get_dlpfc_data(sectionid)
train(adata, lr=1e-3, radius=150, node2vec_p=1, node2vec_q=1, louvain_resolution=.4, components_features=30, walk_length=25)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[0][0].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: dlpfc, slice id: 151508, size: (4384, 33538), cluster: 7.
>>> The graph contains 30082 edges, average 6.861770072992701 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 28426 edges, average 6.484032846715328 edges per node.


>>> node2vec: 100%|██████████| 200/200 [05:00<00:00,  1.50s/it]


>>> spatial model data(features) size: (4384, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:06<00:00, 76.60it/s]


>>> Birch: 41.7593


In [6]:
adata, n_cluster = get_dlpfc_data(sectionid)
train(adata, lr=1e-3, radius=150, node2vec_p=1, node2vec_q=1, louvain_resolution=.6, components_features=30, walk_length=25)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[1][0].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: dlpfc, slice id: 151508, size: (4384, 33538), cluster: 7.
>>> The graph contains 30082 edges, average 6.861770072992701 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 21140 edges, average 4.822080291970803 edges per node.


>>> node2vec: 100%|██████████| 200/200 [05:00<00:00,  1.50s/it]


>>> spatial model data(features) size: (4384, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:06<00:00, 78.49it/s]


>>> Birch: 38.1323


In [7]:
adata, n_cluster = get_dlpfc_data(sectionid)
train(adata, lr=1e-3, radius=150, node2vec_p=1, node2vec_q=1, louvain_resolution=.8, components_features=30, walk_length=25)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[2][0].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: dlpfc, slice id: 151508, size: (4384, 33538), cluster: 7.
>>> The graph contains 30082 edges, average 6.861770072992701 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 20546 edges, average 4.686587591240876 edges per node.


>>> node2vec: 100%|██████████| 200/200 [05:02<00:00,  1.51s/it]


>>> spatial model data(features) size: (4384, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:07<00:00, 69.63it/s]


>>> Birch: 35.5042


In [8]:
adata, n_cluster = get_dlpfc_data(sectionid)
train(adata, lr=1e-3, radius=150, node2vec_p=.25, node2vec_q=4, louvain_resolution=.4, components_features=30, walk_length=25)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[0][0].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: dlpfc, slice id: 151508, size: (4384, 33538), cluster: 7.
>>> The graph contains 30082 edges, average 6.861770072992701 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 28426 edges, average 6.484032846715328 edges per node.


>>> node2vec: 100%|██████████| 200/200 [04:27<00:00,  1.34s/it]


>>> spatial model data(features) size: (4384, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:06<00:00, 73.84it/s]


>>> Birch: 47.8767


In [9]:
adata, n_cluster = get_dlpfc_data(sectionid)
train(adata, lr=1e-3, radius=150, node2vec_p=.25, node2vec_q=4, louvain_resolution=.6, components_features=30, walk_length=25)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[1][0].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: dlpfc, slice id: 151508, size: (4384, 33538), cluster: 7.
>>> The graph contains 30082 edges, average 6.861770072992701 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 21144 edges, average 4.822992700729927 edges per node.


>>> node2vec: 100%|██████████| 200/200 [04:23<00:00,  1.32s/it]


>>> spatial model data(features) size: (4384, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:07<00:00, 67.90it/s]


>>> Birch: 33.9113


In [10]:
adata, n_cluster = get_dlpfc_data(sectionid)
train(adata, lr=1e-3, radius=150, node2vec_p=.25, node2vec_q=4, louvain_resolution=.8, components_features=30, walk_length=25)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[2][0].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: dlpfc, slice id: 151508, size: (4384, 33538), cluster: 7.
>>> The graph contains 30082 edges, average 6.861770072992701 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 20530 edges, average 4.68293795620438 edges per node.


>>> node2vec: 100%|██████████| 200/200 [04:18<00:00,  1.29s/it]


>>> spatial model data(features) size: (4384, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:06<00:00, 73.91it/s]


>>> Birch: 41.4126


In [11]:
adata, n_cluster = get_dlpfc_data(sectionid)
train(adata, lr=1e-3, radius=150, node2vec_p=4, node2vec_q=.25, louvain_resolution=.4, components_features=30, walk_length=35)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[0][1].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: dlpfc, slice id: 151508, size: (4384, 33538), cluster: 7.
>>> The graph contains 30082 edges, average 6.861770072992701 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 28426 edges, average 6.484032846715328 edges per node.


>>> node2vec: 100%|██████████| 200/200 [06:10<00:00,  1.85s/it]


>>> spatial model data(features) size: (4384, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:06<00:00, 77.37it/s]


>>> Birch: 42.8463


In [12]:
adata, n_cluster = get_dlpfc_data(sectionid)
train(adata, lr=1e-3, radius=150, node2vec_p=4, node2vec_q=.25, louvain_resolution=.6, components_features=30, walk_length=35)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[1][1].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: dlpfc, slice id: 151508, size: (4384, 33538), cluster: 7.
>>> The graph contains 30082 edges, average 6.861770072992701 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 21140 edges, average 4.822080291970803 edges per node.


>>> node2vec: 100%|██████████| 200/200 [05:03<00:00,  1.52s/it]


>>> spatial model data(features) size: (4384, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:05<00:00, 83.92it/s]


>>> Birch: 40.5447


In [13]:
adata, n_cluster = get_dlpfc_data(sectionid)
train(adata, lr=1e-3, radius=150, node2vec_p=4, node2vec_q=.25, louvain_resolution=.8, components_features=30, walk_length=35)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[2][1].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: dlpfc, slice id: 151508, size: (4384, 33538), cluster: 7.
>>> The graph contains 30082 edges, average 6.861770072992701 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 20530 edges, average 4.68293795620438 edges per node.


>>> node2vec: 100%|██████████| 200/200 [03:33<00:00,  1.07s/it]


>>> spatial model data(features) size: (4384, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:05<00:00, 85.21it/s]


>>> Birch: 44.2666


In [14]:
adata, n_cluster = get_dlpfc_data(sectionid)
train(adata, lr=1e-3, radius=150, node2vec_p=1, node2vec_q=1, louvain_resolution=.4, components_features=30, walk_length=35)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[0][1].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: dlpfc, slice id: 151508, size: (4384, 33538), cluster: 7.
>>> The graph contains 30082 edges, average 6.861770072992701 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 28426 edges, average 6.484032846715328 edges per node.


>>> node2vec: 100%|██████████| 200/200 [05:21<00:00,  1.61s/it]


>>> spatial model data(features) size: (4384, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:07<00:00, 68.43it/s]


>>> Birch: 40.8241


In [15]:
adata, n_cluster = get_dlpfc_data(sectionid)
train(adata, lr=1e-3, radius=150, node2vec_p=1, node2vec_q=1, louvain_resolution=.6, components_features=30, walk_length=35)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[1][1].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: dlpfc, slice id: 151508, size: (4384, 33538), cluster: 7.
>>> The graph contains 30082 edges, average 6.861770072992701 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 21144 edges, average 4.822992700729927 edges per node.


>>> node2vec: 100%|██████████| 200/200 [08:49<00:00,  2.65s/it]


>>> spatial model data(features) size: (4384, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:12<00:00, 40.85it/s]


>>> Birch: 26.6542


In [16]:
adata, n_cluster = get_dlpfc_data(sectionid)
train(adata, lr=1e-3, radius=150, node2vec_p=1, node2vec_q=1, louvain_resolution=.8, components_features=30, walk_length=35)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[2][1].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: dlpfc, slice id: 151508, size: (4384, 33538), cluster: 7.
>>> The graph contains 30082 edges, average 6.861770072992701 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 20526 edges, average 4.682025547445256 edges per node.


>>> node2vec: 100%|██████████| 200/200 [08:58<00:00,  2.69s/it]


>>> spatial model data(features) size: (4384, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:08<00:00, 62.21it/s]


>>> Birch: 34.2958


In [17]:
adata, n_cluster = get_dlpfc_data(sectionid)
train(adata, lr=1e-3, radius=150, node2vec_p=.25, node2vec_q=4, louvain_resolution=.4, components_features=30, walk_length=35)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[0][1].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: dlpfc, slice id: 151508, size: (4384, 33538), cluster: 7.
>>> The graph contains 30082 edges, average 6.861770072992701 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 28426 edges, average 6.484032846715328 edges per node.


>>> node2vec: 100%|██████████| 200/200 [09:31<00:00,  2.86s/it]


>>> spatial model data(features) size: (4384, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:07<00:00, 63.02it/s]


>>> Birch: 32.2295


In [18]:
adata, n_cluster = get_dlpfc_data(sectionid)
train(adata, lr=1e-3, radius=150, node2vec_p=.25, node2vec_q=4, louvain_resolution=.6, components_features=30, walk_length=35)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[1][1].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: dlpfc, slice id: 151508, size: (4384, 33538), cluster: 7.
>>> The graph contains 30082 edges, average 6.861770072992701 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 21140 edges, average 4.822080291970803 edges per node.


>>> node2vec: 100%|██████████| 200/200 [09:07<00:00,  2.74s/it]


>>> spatial model data(features) size: (4384, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:07<00:00, 69.53it/s]


>>> Birch: 42.9856


In [19]:
adata, n_cluster = get_dlpfc_data(sectionid)
train(adata, lr=1e-3, radius=150, node2vec_p=.25, node2vec_q=4, louvain_resolution=.8, components_features=30, walk_length=35)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[2][1].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: dlpfc, slice id: 151508, size: (4384, 33538), cluster: 7.
>>> The graph contains 30082 edges, average 6.861770072992701 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 20530 edges, average 4.68293795620438 edges per node.


>>> node2vec: 100%|██████████| 200/200 [09:18<00:00,  2.79s/it]


>>> spatial model data(features) size: (4384, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:07<00:00, 64.03it/s]


>>> Birch: 42.1203


In [20]:
adata, n_cluster = get_dlpfc_data(sectionid)
train(adata, lr=1e-3, radius=150, node2vec_p=4, node2vec_q=.25, louvain_resolution=.4, components_features=30, walk_length=45)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[0][2].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: dlpfc, slice id: 151508, size: (4384, 33538), cluster: 7.
>>> The graph contains 30082 edges, average 6.861770072992701 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 28426 edges, average 6.484032846715328 edges per node.


>>> node2vec: 100%|██████████| 200/200 [09:39<00:00,  2.90s/it]


>>> spatial model data(features) size: (4384, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:07<00:00, 67.25it/s]


>>> Birch: 42.6963


In [21]:
adata, n_cluster = get_dlpfc_data(sectionid)
train(adata, lr=1e-3, radius=150, node2vec_p=4, node2vec_q=.25, louvain_resolution=.6, components_features=30, walk_length=45)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[1][2].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: dlpfc, slice id: 151508, size: (4384, 33538), cluster: 7.
>>> The graph contains 30082 edges, average 6.861770072992701 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 21140 edges, average 4.822080291970803 edges per node.


>>> node2vec: 100%|██████████| 200/200 [09:40<00:00,  2.90s/it]


>>> spatial model data(features) size: (4384, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:07<00:00, 70.74it/s]


>>> Birch: 35.0924


In [22]:
adata, n_cluster = get_dlpfc_data(sectionid)
train(adata, lr=1e-3, radius=150, node2vec_p=4, node2vec_q=.25, louvain_resolution=.8, components_features=30, walk_length=45)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[2][2].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: dlpfc, slice id: 151508, size: (4384, 33538), cluster: 7.
>>> The graph contains 30082 edges, average 6.861770072992701 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 20530 edges, average 4.68293795620438 edges per node.


>>> node2vec: 100%|██████████| 200/200 [09:32<00:00,  2.86s/it]


>>> spatial model data(features) size: (4384, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:06<00:00, 72.74it/s]


>>> Birch: 32.6080


In [23]:
adata, n_cluster = get_dlpfc_data(sectionid)
train(adata, lr=1e-3, radius=150, node2vec_p=1, node2vec_q=1, louvain_resolution=.4, components_features=30, walk_length=45)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[0][2].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: dlpfc, slice id: 151508, size: (4384, 33538), cluster: 7.
>>> The graph contains 30082 edges, average 6.861770072992701 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 28426 edges, average 6.484032846715328 edges per node.


>>> node2vec: 100%|██████████| 200/200 [08:53<00:00,  2.67s/it]


>>> spatial model data(features) size: (4384, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:07<00:00, 69.29it/s]


>>> Birch: 31.1642


In [24]:
adata, n_cluster = get_dlpfc_data(sectionid)
train(adata, lr=1e-3, radius=150, node2vec_p=1, node2vec_q=1, louvain_resolution=.6, components_features=30, walk_length=45)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[1][2].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: dlpfc, slice id: 151508, size: (4384, 33538), cluster: 7.
>>> The graph contains 30082 edges, average 6.861770072992701 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 21140 edges, average 4.822080291970803 edges per node.


>>> node2vec: 100%|██████████| 200/200 [07:30<00:00,  2.25s/it]


>>> spatial model data(features) size: (4384, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:07<00:00, 68.94it/s]


>>> Birch: 30.7876


In [25]:
adata, n_cluster = get_dlpfc_data(sectionid)
train(adata, lr=1e-3, radius=150, node2vec_p=1, node2vec_q=1, louvain_resolution=.8, components_features=30, walk_length=45)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[2][2].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: dlpfc, slice id: 151508, size: (4384, 33538), cluster: 7.
>>> The graph contains 30082 edges, average 6.861770072992701 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 20530 edges, average 4.68293795620438 edges per node.


>>> node2vec: 100%|██████████| 200/200 [07:03<00:00,  2.12s/it]


>>> spatial model data(features) size: (4384, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:06<00:00, 75.25it/s]


>>> Birch: 42.5582


In [26]:
adata, n_cluster = get_dlpfc_data(sectionid)
train(adata, lr=1e-3, radius=150, node2vec_p=.25, node2vec_q=4, louvain_resolution=.4, components_features=30, walk_length=45)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[0][2].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: dlpfc, slice id: 151508, size: (4384, 33538), cluster: 7.
>>> The graph contains 30082 edges, average 6.861770072992701 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 28426 edges, average 6.484032846715328 edges per node.


>>> node2vec: 100%|██████████| 200/200 [07:27<00:00,  2.24s/it]


>>> spatial model data(features) size: (4384, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:09<00:00, 51.90it/s]


>>> Birch: 35.1286


In [27]:
adata, n_cluster = get_dlpfc_data(sectionid)
train(adata, lr=1e-3, radius=150, node2vec_p=.25, node2vec_q=4, louvain_resolution=.6, components_features=30, walk_length=45)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[1][2].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: dlpfc, slice id: 151508, size: (4384, 33538), cluster: 7.
>>> The graph contains 30082 edges, average 6.861770072992701 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 21144 edges, average 4.822992700729927 edges per node.


>>> node2vec: 100%|██████████| 200/200 [07:39<00:00,  2.30s/it]


>>> spatial model data(features) size: (4384, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:06<00:00, 74.82it/s]


>>> Birch: 33.2340


In [28]:
adata, n_cluster = get_dlpfc_data(sectionid)
train(adata, lr=1e-3, radius=150, node2vec_p=.25, node2vec_q=4, louvain_resolution=.8, components_features=30, walk_length=45)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[2][2].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: dlpfc, slice id: 151508, size: (4384, 33538), cluster: 7.
>>> The graph contains 30082 edges, average 6.861770072992701 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 20526 edges, average 4.682025547445256 edges per node.


>>> node2vec: 100%|██████████| 200/200 [07:49<00:00,  2.35s/it]


>>> spatial model data(features) size: (4384, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:06<00:00, 75.12it/s]


>>> Birch: 42.9656


In [29]:
import numpy as np

print(np.array(result))

[[[35.53200543 41.75925049 47.87665638]
  [42.84628696 40.82408328 32.22948983]
  [42.69631273 31.16423756 35.12861978]]

 [[34.55766253 38.13227834 33.91126045]
  [40.54468251 26.6541765  42.9855546 ]
  [35.0924032  30.78761582 33.23398466]]

 [[43.61440209 35.50421247 41.41263031]
  [44.26658809 34.29583017 42.12025039]
  [32.60796901 42.55816388 42.96564862]]]
