In [1]:
from model.test import train
from dataset import *
from tools import evaluate

from sklearn import metrics
from sklearn.preprocessing import LabelEncoder 
from sklearn.cluster import KMeans, BisectingKMeans, Birch, SpectralClustering, AgglomerativeClustering, FeatureAgglomeration

result = [[[], [], []], [[], [], []], [[], [], []]]

In [2]:
adata, n_cluster = get_human_breast_cancer_data()
train(adata, lr=1e-3, radius=350, node2vec_p=4, node2vec_q=.25, louvain_resolution=.4, components_features=30, walk_length=25)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[0][0].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: human_breast_cancer, size: (3798, 36601), cluster: 20.
>>> The graph contains 25862 edges, average 6.809373354397051 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 23002 edges, average 6.056345444971037 edges per node.


>>> node2vec: 100%|██████████| 200/200 [05:02<00:00,  1.51s/it]


>>> spatial model data(features) size: (3798, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:06<00:00, 75.10it/s]


>>> Birch: 55.8994


In [3]:
adata, n_cluster = get_human_breast_cancer_data()
train(adata, lr=1e-3, radius=350, node2vec_p=4, node2vec_q=.25, louvain_resolution=.6, components_features=30, walk_length=25)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[1][0].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: human_breast_cancer, size: (3798, 36601), cluster: 20.
>>> The graph contains 25862 edges, average 6.809373354397051 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 22990 edges, average 6.05318588730911 edges per node.


>>> node2vec: 100%|██████████| 200/200 [04:17<00:00,  1.29s/it]


>>> spatial model data(features) size: (3798, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:05<00:00, 88.54it/s]


>>> Birch: 53.3593


In [4]:
adata, n_cluster = get_human_breast_cancer_data()
train(adata, lr=1e-3, radius=350, node2vec_p=4, node2vec_q=.25, louvain_resolution=.8, components_features=30, walk_length=25)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[2][0].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: human_breast_cancer, size: (3798, 36601), cluster: 20.
>>> The graph contains 25862 edges, average 6.809373354397051 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 21802 edges, average 5.740389678778304 edges per node.


>>> node2vec: 100%|██████████| 200/200 [03:38<00:00,  1.09s/it]


>>> spatial model data(features) size: (3798, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:05<00:00, 86.87it/s]


>>> Birch: 57.6835


In [5]:
adata, n_cluster = get_human_breast_cancer_data()
train(adata, lr=1e-3, radius=350, node2vec_p=1, node2vec_q=1, louvain_resolution=.4, components_features=30, walk_length=25)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[0][0].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: human_breast_cancer, size: (3798, 36601), cluster: 20.
>>> The graph contains 25862 edges, average 6.809373354397051 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 23002 edges, average 6.056345444971037 edges per node.


>>> node2vec: 100%|██████████| 200/200 [02:09<00:00,  1.54it/s]


>>> spatial model data(features) size: (3798, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:05<00:00, 91.03it/s]


>>> Birch: 61.0900


In [6]:
adata, n_cluster = get_human_breast_cancer_data()
train(adata, lr=1e-3, radius=350, node2vec_p=1, node2vec_q=1, louvain_resolution=.6, components_features=30, walk_length=25)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[1][0].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: human_breast_cancer, size: (3798, 36601), cluster: 20.
>>> The graph contains 25862 edges, average 6.809373354397051 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 22990 edges, average 6.05318588730911 edges per node.


>>> node2vec: 100%|██████████| 200/200 [04:26<00:00,  1.33s/it]


>>> spatial model data(features) size: (3798, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:05<00:00, 85.77it/s]


>>> Birch: 54.7457


In [7]:
adata, n_cluster = get_human_breast_cancer_data()
train(adata, lr=1e-3, radius=350, node2vec_p=1, node2vec_q=1, louvain_resolution=.8, components_features=30, walk_length=25)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[2][0].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: human_breast_cancer, size: (3798, 36601), cluster: 20.
>>> The graph contains 25862 edges, average 6.809373354397051 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 21802 edges, average 5.740389678778304 edges per node.


>>> node2vec: 100%|██████████| 200/200 [01:40<00:00,  1.98it/s]


>>> spatial model data(features) size: (3798, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:05<00:00, 90.45it/s]


>>> Birch: 53.1889


In [8]:
adata, n_cluster = get_human_breast_cancer_data()
train(adata, lr=1e-3, radius=350, node2vec_p=.25, node2vec_q=4, louvain_resolution=.4, components_features=30, walk_length=25)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[0][0].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: human_breast_cancer, size: (3798, 36601), cluster: 20.
>>> The graph contains 25862 edges, average 6.809373354397051 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 23002 edges, average 6.056345444971037 edges per node.


>>> node2vec: 100%|██████████| 200/200 [04:33<00:00,  1.37s/it]


>>> spatial model data(features) size: (3798, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:05<00:00, 90.47it/s]


>>> Birch: 56.4780


In [9]:
adata, n_cluster = get_human_breast_cancer_data()
train(adata, lr=1e-3, radius=350, node2vec_p=.25, node2vec_q=4, louvain_resolution=.6, components_features=30, walk_length=25)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[1][0].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: human_breast_cancer, size: (3798, 36601), cluster: 20.
>>> The graph contains 25862 edges, average 6.809373354397051 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 22990 edges, average 6.05318588730911 edges per node.


>>> node2vec: 100%|██████████| 200/200 [04:45<00:00,  1.43s/it]


>>> spatial model data(features) size: (3798, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:05<00:00, 90.60it/s]


>>> Birch: 56.1768


In [10]:
adata, n_cluster = get_human_breast_cancer_data()
train(adata, lr=1e-3, radius=350, node2vec_p=.25, node2vec_q=4, louvain_resolution=.8, components_features=30, walk_length=25)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[2][0].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: human_breast_cancer, size: (3798, 36601), cluster: 20.
>>> The graph contains 25862 edges, average 6.809373354397051 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 21802 edges, average 5.740389678778304 edges per node.


>>> node2vec: 100%|██████████| 200/200 [04:14<00:00,  1.27s/it]


>>> spatial model data(features) size: (3798, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:05<00:00, 85.86it/s]


>>> Birch: 53.9296


In [11]:
adata, n_cluster = get_human_breast_cancer_data()
train(adata, lr=1e-3, radius=350, node2vec_p=4, node2vec_q=.25, louvain_resolution=.4, components_features=30, walk_length=35)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[0][1].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: human_breast_cancer, size: (3798, 36601), cluster: 20.
>>> The graph contains 25862 edges, average 6.809373354397051 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 23002 edges, average 6.056345444971037 edges per node.


>>> node2vec: 100%|██████████| 200/200 [07:38<00:00,  2.29s/it]


>>> spatial model data(features) size: (3798, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:06<00:00, 73.51it/s]


>>> Birch: 55.6238


In [12]:
adata, n_cluster = get_human_breast_cancer_data()
train(adata, lr=1e-3, radius=350, node2vec_p=4, node2vec_q=.25, louvain_resolution=.6, components_features=30, walk_length=35)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[1][1].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: human_breast_cancer, size: (3798, 36601), cluster: 20.
>>> The graph contains 25862 edges, average 6.809373354397051 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 22990 edges, average 6.05318588730911 edges per node.


>>> node2vec: 100%|██████████| 200/200 [07:02<00:00,  2.11s/it]


>>> spatial model data(features) size: (3798, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:05<00:00, 85.07it/s]


>>> Birch: 56.7024


In [13]:
adata, n_cluster = get_human_breast_cancer_data()
train(adata, lr=1e-3, radius=350, node2vec_p=4, node2vec_q=.25, louvain_resolution=.8, components_features=30, walk_length=35)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[2][1].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: human_breast_cancer, size: (3798, 36601), cluster: 20.
>>> The graph contains 25862 edges, average 6.809373354397051 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 21802 edges, average 5.740389678778304 edges per node.


>>> node2vec: 100%|██████████| 200/200 [07:16<00:00,  2.18s/it]


>>> spatial model data(features) size: (3798, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:05<00:00, 94.66it/s]


>>> Birch: 51.8677


In [14]:
adata, n_cluster = get_human_breast_cancer_data()
train(adata, lr=1e-3, radius=350, node2vec_p=1, node2vec_q=1, louvain_resolution=.4, components_features=30, walk_length=35)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[0][1].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: human_breast_cancer, size: (3798, 36601), cluster: 20.
>>> The graph contains 25862 edges, average 6.809373354397051 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 23002 edges, average 6.056345444971037 edges per node.


>>> node2vec: 100%|██████████| 200/200 [06:18<00:00,  1.89s/it]


>>> spatial model data(features) size: (3798, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:05<00:00, 92.70it/s]


>>> Birch: 58.5982


In [15]:
adata, n_cluster = get_human_breast_cancer_data()
train(adata, lr=1e-3, radius=350, node2vec_p=1, node2vec_q=1, louvain_resolution=.6, components_features=30, walk_length=35)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[1][1].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: human_breast_cancer, size: (3798, 36601), cluster: 20.
>>> The graph contains 25862 edges, average 6.809373354397051 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 22990 edges, average 6.05318588730911 edges per node.


>>> node2vec: 100%|██████████| 200/200 [11:33<00:00,  3.47s/it]


>>> spatial model data(features) size: (3798, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:07<00:00, 71.36it/s]


>>> Birch: 55.0471


In [16]:
adata, n_cluster = get_human_breast_cancer_data()
train(adata, lr=1e-3, radius=350, node2vec_p=1, node2vec_q=1, louvain_resolution=.8, components_features=30, walk_length=35)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[2][1].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: human_breast_cancer, size: (3798, 36601), cluster: 20.
>>> The graph contains 25862 edges, average 6.809373354397051 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 21802 edges, average 5.740389678778304 edges per node.


>>> node2vec: 100%|██████████| 200/200 [12:28<00:00,  3.74s/it]


>>> spatial model data(features) size: (3798, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:06<00:00, 74.14it/s]


>>> Birch: 54.2118


In [17]:
adata, n_cluster = get_human_breast_cancer_data()
train(adata, lr=1e-3, radius=350, node2vec_p=.25, node2vec_q=4, louvain_resolution=.4, components_features=30, walk_length=35)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[0][1].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: human_breast_cancer, size: (3798, 36601), cluster: 20.
>>> The graph contains 25862 edges, average 6.809373354397051 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 23002 edges, average 6.056345444971037 edges per node.


>>> node2vec: 100%|██████████| 200/200 [07:18<00:00,  2.19s/it]


>>> spatial model data(features) size: (3798, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:07<00:00, 68.80it/s]


>>> Birch: 54.5558


In [18]:
adata, n_cluster = get_human_breast_cancer_data()
train(adata, lr=1e-3, radius=350, node2vec_p=.25, node2vec_q=4, louvain_resolution=.6, components_features=30, walk_length=35)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[1][1].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: human_breast_cancer, size: (3798, 36601), cluster: 20.
>>> The graph contains 25862 edges, average 6.809373354397051 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 22990 edges, average 6.05318588730911 edges per node.


>>> node2vec: 100%|██████████| 200/200 [08:28<00:00,  2.54s/it]


>>> spatial model data(features) size: (3798, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:06<00:00, 74.75it/s]


>>> Birch: 57.3281


In [19]:
adata, n_cluster = get_human_breast_cancer_data()
train(adata, lr=1e-3, radius=350, node2vec_p=.25, node2vec_q=4, louvain_resolution=.8, components_features=30, walk_length=35)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[2][1].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: human_breast_cancer, size: (3798, 36601), cluster: 20.
>>> The graph contains 25862 edges, average 6.809373354397051 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 21802 edges, average 5.740389678778304 edges per node.


>>> node2vec: 100%|██████████| 200/200 [07:27<00:00,  2.24s/it]


>>> spatial model data(features) size: (3798, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:07<00:00, 66.83it/s]


>>> Birch: 56.3823


In [20]:
adata, n_cluster = get_human_breast_cancer_data()
train(adata, lr=1e-3, radius=350, node2vec_p=4, node2vec_q=.25, louvain_resolution=.4, components_features=30, walk_length=45)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[0][2].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: human_breast_cancer, size: (3798, 36601), cluster: 20.
>>> The graph contains 25862 edges, average 6.809373354397051 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 23002 edges, average 6.056345444971037 edges per node.


>>> node2vec: 100%|██████████| 200/200 [06:29<00:00,  1.95s/it]


>>> spatial model data(features) size: (3798, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:07<00:00, 69.52it/s]


>>> Birch: 58.6888


In [21]:
adata, n_cluster = get_human_breast_cancer_data()
train(adata, lr=1e-3, radius=350, node2vec_p=4, node2vec_q=.25, louvain_resolution=.6, components_features=30, walk_length=45)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[1][2].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: human_breast_cancer, size: (3798, 36601), cluster: 20.
>>> The graph contains 25862 edges, average 6.809373354397051 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 22990 edges, average 6.05318588730911 edges per node.


>>> node2vec: 100%|██████████| 200/200 [05:51<00:00,  1.76s/it]


>>> spatial model data(features) size: (3798, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:06<00:00, 80.46it/s]


>>> Birch: 58.9662


In [22]:
adata, n_cluster = get_human_breast_cancer_data()
train(adata, lr=1e-3, radius=350, node2vec_p=4, node2vec_q=.25, louvain_resolution=.8, components_features=30, walk_length=45)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[2][2].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: human_breast_cancer, size: (3798, 36601), cluster: 20.
>>> The graph contains 25862 edges, average 6.809373354397051 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 21802 edges, average 5.740389678778304 edges per node.


>>> node2vec: 100%|██████████| 200/200 [06:13<00:00,  1.87s/it]


>>> spatial model data(features) size: (3798, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:06<00:00, 78.13it/s]


>>> Birch: 56.0607


In [23]:
adata, n_cluster = get_human_breast_cancer_data()
train(adata, lr=1e-3, radius=350, node2vec_p=1, node2vec_q=1, louvain_resolution=.4, components_features=30, walk_length=45)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[0][2].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: human_breast_cancer, size: (3798, 36601), cluster: 20.
>>> The graph contains 25862 edges, average 6.809373354397051 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 23002 edges, average 6.056345444971037 edges per node.


>>> node2vec: 100%|██████████| 200/200 [06:10<00:00,  1.85s/it]


>>> spatial model data(features) size: (3798, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:06<00:00, 78.01it/s]


>>> Birch: 55.9215


In [24]:
adata, n_cluster = get_human_breast_cancer_data()
train(adata, lr=1e-3, radius=350, node2vec_p=1, node2vec_q=1, louvain_resolution=.6, components_features=30, walk_length=45)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[1][2].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: human_breast_cancer, size: (3798, 36601), cluster: 20.
>>> The graph contains 25862 edges, average 6.809373354397051 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 22990 edges, average 6.05318588730911 edges per node.


>>> node2vec: 100%|██████████| 200/200 [07:13<00:00,  2.17s/it]


>>> spatial model data(features) size: (3798, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:06<00:00, 76.23it/s]


>>> Birch: 60.5149


In [25]:
adata, n_cluster = get_human_breast_cancer_data()
train(adata, lr=1e-3, radius=350, node2vec_p=1, node2vec_q=1, louvain_resolution=.8, components_features=30, walk_length=45)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[2][2].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: human_breast_cancer, size: (3798, 36601), cluster: 20.
>>> The graph contains 25862 edges, average 6.809373354397051 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 21802 edges, average 5.740389678778304 edges per node.


>>> node2vec: 100%|██████████| 200/200 [08:21<00:00,  2.51s/it]


>>> spatial model data(features) size: (3798, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:06<00:00, 79.77it/s]


>>> Birch: 57.9775


In [26]:
adata, n_cluster = get_human_breast_cancer_data()
train(adata, lr=1e-3, radius=350, node2vec_p=.25, node2vec_q=4, louvain_resolution=.4, components_features=30, walk_length=45)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[0][2].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: human_breast_cancer, size: (3798, 36601), cluster: 20.
>>> The graph contains 25862 edges, average 6.809373354397051 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 23002 edges, average 6.056345444971037 edges per node.


>>> node2vec: 100%|██████████| 200/200 [07:17<00:00,  2.19s/it]


>>> spatial model data(features) size: (3798, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:06<00:00, 77.23it/s]


>>> Birch: 54.5994


In [27]:
adata, n_cluster = get_human_breast_cancer_data()
train(adata, lr=1e-3, radius=350, node2vec_p=.25, node2vec_q=4, louvain_resolution=.6, components_features=30, walk_length=45)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[1][2].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: human_breast_cancer, size: (3798, 36601), cluster: 20.
>>> The graph contains 25862 edges, average 6.809373354397051 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 22990 edges, average 6.05318588730911 edges per node.


>>> node2vec: 100%|██████████| 200/200 [06:48<00:00,  2.04s/it]


>>> spatial model data(features) size: (3798, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:06<00:00, 78.26it/s]


>>> Birch: 54.3996


In [28]:
adata, n_cluster = get_human_breast_cancer_data()
train(adata, lr=1e-3, radius=350, node2vec_p=.25, node2vec_q=4, louvain_resolution=.8, components_features=30, walk_length=45)

label = LabelEncoder().fit_transform(adata.obs['cluster'])
pred = LabelEncoder().fit_transform([str(x) for x in Birch(n_clusters=n_cluster).fit(adata.obsm['embedding']).predict(adata.obsm['embedding'])])
ari_score = metrics.adjusted_rand_score(label, pred) * 100
print('>>> %s: %.4f' % ('Birch', ari_score))
result[2][2].append(ari_score)

/mnt/5280e/twang/.conda/envs/torch+pyg/lib/python3.8/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


>>> dataset name: human_breast_cancer, size: (3798, 36601), cluster: 20.
>>> The graph contains 25862 edges, average 6.809373354397051 edges per node.
>>> Building spatial graph success!
>>> use louvain to modify spatial graph
         Falling back to preprocessing with `sc.pp.pca` and default params.
>>> finish louvain, begin to prune graph
>>> pruned graph contains 21802 edges, average 5.740389678778304 edges per node.


>>> node2vec: 100%|██████████| 200/200 [06:45<00:00,  2.03s/it]


>>> spatial model data(features) size: (3798, 3000)


>>> training spatial model: 100%|██████████| 500/500 [00:06<00:00, 78.92it/s]


>>> Birch: 58.2200


In [29]:
import numpy as np

print(np.array(result))

[[[55.89935398 61.08995278 56.47804805]
  [55.62378249 58.59818893 54.55580008]
  [58.68876148 55.92151361 54.59940078]]

 [[53.35931126 54.74565315 56.17681013]
  [56.70244274 55.0471376  57.32812206]
  [58.96615762 60.5149453  54.39962904]]

 [[57.68350867 53.18888079 53.92958611]
  [51.86765537 54.21181434 56.3822851 ]
  [56.06070288 57.97751078 58.21995079]]]
